apiVersion: batch/v1
kind: Job
metadata:
  name: add-admin-user
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app:
      {{- include "nebulous-gui-controller.labels" . | nindent 4 }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ['sh', '-c', 'until nc -z nebulous-gui-controller-mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: add-admin-user
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["node"]
        args: ["app.js", "@apostrophecms/user:add", "{{ .Values.apostropheCMS.user.name }}", "{{ .Values.apostropheCMS.user.password }}"]
      restartPolicy: Never
  backoffLimit: 4
