{{ if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nebulous-gui-controller.fullname" . }}-mongodb
  labels:
    {{- include "nebulous-gui-controller.mongodb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nebulous-gui-controller.mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nebulous-gui-controller.mongodb.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-mongo
          image: "docker.io/mongodb/mongodb-community-server:5.0.15-ubuntu2004"
          command: [ "mongosh", "--file", "/docker-entrypoint-initdb.d/init.js" ]
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mongodb
          image: "docker.io/mongodb/mongodb-community-server:4.4.29-ubuntu2004"
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: nebulous
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: mongodb-init-script
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulous-gui-controller.fullname" . }}-mongodb
  labels:
    {{- include "nebulous-gui-controller.mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "nebulous-gui-controller.mongodb.selectorLabels" . | nindent 4 }}
{{ end }}
